---
  - name: Configure User environment
    lineinfile:
      dest: /root/.bashrc
      create: true
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - {regexp: "^.*PATH.*", line: "export PATH=$PATH:~/go/bin:/root/.local/bin"}
      - {regexp: "^export GOPATH", line: "export GOPATH=~/go"}
      - {regexp: "^.*PROMPT_COMMAND.*", line: ""}
