---
  - name: Install packages
    package: name={{ item }} state=present
    with_items:
      - tmux
      - joe
      - podman
      - go
      - libvirt
      - libvirt-daemon-driver-qemu
      - qemu-kvm
      - rsync
