---
  - name: Install packages
    package: name={{ item }} state=present
    with_items:
      - tmux
      - joe
      - podman
      - go
      - libvirt
      - libvirt-daemon-driver-qemu
      - qemu-kvm
      - rsync
      - tuned
      - git

  - name: Enable helpful services
    service: name={{ item }} enabled=yes state=started
    with_items:
      - tuned
      - fstrim.timer
      - libvirtd
    ignore_errors: true

  - name: Set tuned profile to virtual-host
    shell: /usr/sbin/tuned-adm profile virtual-host
