---
  - name: Run command {{ item }} on host
    shell: "{{item}}"
    with_items:
      - /usr/bin/go install sigs.k8s.io/kind@v0.17
      - curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh | bash
      - curl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        >/usr/bin/kubectl
      - chmod +x /usr/bin/kubectl
      # - groupadd docker
      # - newgrp libvirt
      # - usermod -aG qemu,libvirt $(id -un)
      - systemctl enable --now libvirtd
      # - usermod -aG docker $(id -un)
      # - systemctl restart docker
      - dnf -y copr enable karmab/kcli
      - dnf -y install kcli
      - virsh pool-define-as default dir --target /var/lib/libvirt/images
      - virsh pool-build default
      - virsh pool-start default
      - virsh pool-autostart default
      # - for command in oc openshift-install; do kcli download ${command} ;mv ${command} /usr/bin/; done
      # - [ -f /root/.ssh/id_rsa ] || ssh-keygen -P '' -f /root/.ssh/id_rsa
    ignore_errors: true
