---
  - name: Deploy OCM on the hub
    block:
      - name: Report on Hub
        debug:
          msg: "I am HUUUUUUUUUUB"

      - name: Set kubectl context for HUB
        shell: kubectl  config use-context kind-hub

      - name: Deploy OCM on the Hub
        shell: clusteradm init --wait

      - name: Deploy OCM  app-lifecycle Addon
        shell: clusteradm install hub-addon --names application-manager

      - name: Deploy OCM  Governance policty Addon
        shell: clusteradm install hub-addon --names governance-policy-framework

    when: hub == True
