---
  - hosts: all
    user: root
    strategy: free

    vars:
      console_keymap: en
      console_font: eurlatgr
      system_locale: en_US.UTF-8
      root_shell: /bin/bash
      domain: "{{ ansible_nodename.split('.')[1:] | join('.') }}"
      keys:
        - key: "{{ sshkey }}"

    tasks:
      - name: Edit /etc/hosts to remove entry for the hub to avoid kind deployment issues
        lineinfile:
          path: /etc/hosts
          regexp: ".*hub-control-plane"
          state: absent

      - name: Get kind clusters
        shell: "kind get clusters 2>&1|grep -v podman"
        register: clusters

      - name: Delete kind clusters
        shell: kind delete cluster --name {{item}};
        with_items: "{{ clusters.stdout_lines }}"

      - name: Flush handlers
        meta: flush_handlers

    handlers:
      - name: Restart monit
        service:
          name: monit
          state: restarted
        when: monit

      - name: Restart systemd
        shell: systemctl daemon-reload

      - name: Restart sshd
        service:
          name: sshd
          state: restarted

      - name: Restart systemd-journald
        service:
          name: systemd-journald
          state: restarted
